### ISSUE TITLE
“个性化设置”中用于输入数字的 input type 为 tel 导致手机端使用电话专用键盘，无法输入小数点

### ISSUE THREAD

**Issue by Tsuk1ko** [NathanKun/resonance-columba#103]
<details>
<summary>图</summary>

![](https://github.com/NathanKun/resonance-columba/assets/24877906/f64f99a2-9071-4875-98c2-6642712a6d1c)
</details>

个人认为还是 number 好点？而且有个好处是可以响应键盘的上和下，在调整城市声望等级的时候挺方便的

如果是介意右侧的上下箭头按钮，其实可以通过 css 隐藏

```css
input[type='number']::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
input[type='number'] {
  -moz-appearance: textfield;
}
```
